#!/usr/bin/env bash
# Picks a Whisper model + compose profile for this machine's hardware and
# writes .env for compose.yaml. Safe to re-run; it just overwrites .env.
#
#   ./setup.sh              # detect, write .env, print Marvis config
#   ./setup.sh --self-test  # check the tier logic, touch nothing
#
# See ../docs/whisper-setup.md.
set -euo pipefail

SPEACHES_VERSION="0.8.3"
WHISPER_PORT="${WHISPER_PORT:-8000}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# VRAM (MiB) -> "model_id compute_type". Model IDs verified to exist on
# HuggingFace; speaches pulls them from there by ID.
#
# turbo is 809M params vs large-v3's 1550M, at close to the same accuracy —
# it is the better default wherever it fits, not a downgrade.
pick_model() {
  local vram_mib="$1"
  if   (( vram_mib >= 10240 )); then echo "deepdml/faster-whisper-large-v3-turbo-ct2 float16"
  elif (( vram_mib >=  6144 )); then echo "Systran/faster-distil-whisper-large-v3 float16"
  elif (( vram_mib >=  4096 )); then echo "Systran/faster-whisper-small float16"
  else                               echo "Systran/faster-whisper-base int8"
  fi
}

self_test() {
  local fails=0
  check() { # expected_model vram
    local got; got="$(pick_model "$2" | cut -d' ' -f1)"
    if [[ "$got" != "$1" ]]; then
      echo "FAIL: ${2}MiB -> $got (expected $1)" >&2; fails=1
    fi
  }
  check "deepdml/faster-whisper-large-v3-turbo-ct2" 24576  # 24GB
  check "deepdml/faster-whisper-large-v3-turbo-ct2" 10240  # boundary
  check "Systran/faster-distil-whisper-large-v3"    10239  # just under
  check "Systran/faster-distil-whisper-large-v3"     6144  # boundary
  check "Systran/faster-whisper-small"               6143
  check "Systran/faster-whisper-small"               4096  # boundary
  check "Systran/faster-whisper-base"                4095
  check "Systran/faster-whisper-base"                   0
  (( fails == 0 )) && echo "pick_model: all checks passed"
  return "$fails"
}

if [[ "${1:-}" == "--self-test" ]]; then
  self_test
  exit $?
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found. Install Docker, or use the native path in ../docs/whisper-setup.md" >&2
  exit 1
fi

# nvidia-smi absent, or present but failing (driver mismatch, no GPU in this
# container/VM) both mean the same thing here: no usable GPU. Never fail hard.
vram_mib=0
gpu_name=""
if command -v nvidia-smi >/dev/null 2>&1; then
  gpu_line="$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -n 1 || true)"
  if [[ -n "$gpu_line" ]]; then
    gpu_name="$(echo "$gpu_line" | cut -d',' -f1 | xargs)"
    # "10240 MiB" -> 10240. Strip anything non-numeric.
    vram_mib="$(echo "$gpu_line" | cut -d',' -f2 | tr -cd '0-9')"
    vram_mib="${vram_mib:-0}"
  fi
fi

if (( vram_mib > 0 )); then
  profile="gpu"
  echo "GPU detected: ${gpu_name} (${vram_mib} MiB VRAM)"
  # A driver alone is not enough; the container needs the NVIDIA Container
  # Toolkit. Warn rather than block — CDI-based setups don't always register
  # a visible "nvidia" runtime.
  if ! command -v nvidia-ctk >/dev/null 2>&1 \
     && ! docker info --format '{{json .Runtimes}}' 2>/dev/null | grep -q nvidia; then
    echo "  WARNING: NVIDIA Container Toolkit not detected. The container may not see the GPU."
    echo "           Verify with: docker run --rm --gpus all ubuntu nvidia-smi"
    echo "           Install: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html"
  fi
else
  profile="cpu"
  echo "No NVIDIA GPU detected — using the CPU profile."
  echo "  Expect slower-than-realtime transcription on long recordings."
fi

read -r model compute_type <<< "$(pick_model "$vram_mib")"

cat > "${SCRIPT_DIR}/.env" <<EOF
# Generated by setup.sh — re-run it to regenerate, or edit by hand.
COMPOSE_PROFILES=${profile}
SPEACHES_VERSION=${SPEACHES_VERSION}
WHISPER_MODEL=${model}
WHISPER_COMPUTE_TYPE=${compute_type}
WHISPER_PORT=${WHISPER_PORT}
EOF

# Tailscale IP is what the laptop should actually point at; fall back to a
# placeholder rather than printing a localhost URL that won't work remotely.
tailscale_ip=""
if command -v tailscale >/dev/null 2>&1; then
  tailscale_ip="$(tailscale ip -4 2>/dev/null | head -n 1 || true)"
fi
host_for_url="${tailscale_ip:-<this-machine-ip>}"

cat <<EOF

Wrote ${SCRIPT_DIR}/.env
  profile: ${profile}
  model:   ${model}
  compute: ${compute_type}

Start it:
  cd "${SCRIPT_DIR}" && docker compose up -d

First run downloads the model (multiple GB) — watch progress with:
  docker compose logs -f

Then in Marvis, Settings -> AI:
  Transcription URL:   http://${host_for_url}:${WHISPER_PORT}/v1
  Transcription model: ${model}
  API key:             (leave blank)
EOF

if [[ -z "$tailscale_ip" ]]; then
  echo
  echo "Note: tailscale not found here. Run 'tailscale ip -4' on this machine"
  echo "      to get the address the laptop should use."
fi

echo
echo "Before exposing port ${WHISPER_PORT}, read the firewall note in ../docs/whisper-setup.md"
